/**
 * Schema fragments for the collaborative-text field type.
 *
 * A derived body declared with `e.collaborativeText()` is backed by a
 * document entity carrying one declared map field (`content`) whose
 * keys are run ids. The document entity is generated by `defineSchema`
 * when it expands a derived field, so apps never name it unless they
 * want per-field permission granularity.
 */

import { Type } from "@sinclair/typebox";

import { buildEntityDef, e, type EntityDef, type MapSchema } from "../../schema/entity";

/** Default document entity name backing a derived collaborative-text body. */
export const DEFAULT_DOCUMENT_ENTITY = "text_document";

/** Field on the document entity holding the run map. */
export const DOC_CONTENT_FIELD = "content";

/**
 * True when a relationship or a derived-field marker names a
 * collaborative-text body. One predicate so the discriminator string
 * lives in exactly one place.
 */
export const isCollaborativeText = (value: { readonly kind?: string }): boolean =>
  value.kind === "collaborative-text";

/**
 * TypeBox shape of a run as it rides inside the document's `content`
 * map. Mirrors the `RunNode` value type in `tree.ts`; kept next to the
 * schema layer so the document entity validates like any other field.
 */
export const RunNodeSchema = Type.Object({
  id: Type.String(),
  hlc: Type.String(),
  actorId: Type.String(),
  text: Type.String(),
  parentId: Type.String(),
  deleted: Type.Boolean(),
});

/**
 * One entry in the `content` map: a live run, or its tombstone
 * (`null`). The tombstone participates in the per-key merge so a late
 * write can still beat it; the projection is what hides a tombstoned
 * key.
 */
export const RunFieldValueSchema = Type.Union([RunNodeSchema, Type.Null()]);

/** Field map of a generated document entity. */
export type TextDocumentFields = {
  readonly content: ReturnType<typeof e.map<typeof RunFieldValueSchema>>;
};

/**
 * Build the document entity for a derived body under `name`. Uses the
 * unchecked factory because the generated name is dynamic (the shared
 * default, or the `entity` option on `e.collaborativeText`).
 */
export function buildTextDocumentEntity<N extends string>(
  name: N,
): EntityDef<TextDocumentFields, N> {
  return buildEntityDef(name, {
    [DOC_CONTENT_FIELD]: e.map(RunFieldValueSchema),
  }) as EntityDef<TextDocumentFields, N>;
}

/** The shared document entity that `e.collaborativeText()` defaults to. */
export const textDocumentEntity: EntityDef<TextDocumentFields, typeof DEFAULT_DOCUMENT_ENTITY> =
  buildTextDocumentEntity(DEFAULT_DOCUMENT_ENTITY);

export type { MapSchema };
